<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>lowcode</artifactId>
        <groupId>com.wuji</groupId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>lowcode_service</artifactId>

    <dependencies>
        <dependency>
            <artifactId>lowcode_common</artifactId>
            <groupId>com.wuji</groupId>
        </dependency>
        <dependency>
            <groupId>com.wuji</groupId>
            <artifactId>lowcode_workflow</artifactId>
<!--            <exclusions>-->
<!--                <exclusion>-->
<!--                    <artifactId>lowcode_system</artifactId>-->
<!--                    <groupId>com.wuji</groupId>-->
<!--                </exclusion>-->
<!--            </exclusions>-->
        </dependency>
<!--        <dependency>-->
<!--            <artifactId>lowcode_system</artifactId>-->
<!--            <groupId>com.wuji</groupId>-->
<!--            <version>1.0.0-SNAPSHOT</version>-->
<!--        </dependency>-->
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-test</artifactId>
        </dependency>
        <dependency>
            <groupId>org.flowable</groupId>
            <artifactId>flowable-json-converter</artifactId>
        </dependency>

        <dependency>
            <groupId>org.flowable</groupId>
            <artifactId>flowable-bpmn-layout</artifactId>
        </dependency>
        <dependency>
            <artifactId>lowcode_quartz</artifactId>
            <groupId>com.wuji</groupId>
        </dependency>
        <dependency>
            <groupId>net.sf.jxls</groupId>
            <artifactId>jxls-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jxls</groupId>
            <artifactId>jxls-poi</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jxls</groupId>
            <artifactId>jxls</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-jexl</artifactId>
        </dependency>
        <dependency>
            <groupId>org.mongodb</groupId>
            <artifactId>mongodb-crypt</artifactId>
            <version>1.8.0</version> <!-- 确保与你的驱动版本匹配 -->
        </dependency>
        <dependency>
            <groupId>com.wuji</groupId>
            <artifactId>lowcode_openplat</artifactId>
        </dependency>
        <dependency>
            <groupId>com.deepoove</groupId>
            <artifactId>poi-tl</artifactId>
        </dependency>
        <dependency>
            <groupId>com.wuji</groupId>
            <artifactId>lowcode_plugin</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>
    </dependencies>

</project>